apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sql-pv-claim
  namespace: hanan-tawazun
  labels:
    app: sql
spec:
  #storageClassName: local-path
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi