apiVersion: v1
kind: PersistentVolume
metadata:
  name: sql-pv
  namespace: hanan-tawazun
  labels:
    type: local
    app: sql
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"